# Generated by Django 3.1.6 on 2021-03-18 21:01

from django.db import connection
from django.db import migrations


def create_indexes(apps, schema_editor):
    create_index_query = """
    CREATE INDEX IF NOT EXISTS opi_companies_idx ON ov.or_podanie_issues (company_id);
    CREATE INDEX IF NOT EXISTS zii_companies_idx ON ov.znizenie_imania_issues (company_id);
    CREATE INDEX IF NOT EXISTS li_companies_idx ON ov.likvidator_issues (company_id);
    CREATE INDEX IF NOT EXISTS kvi_companies_idx ON ov.konkurz_vyrovnanie_issues (company_id);
    CREATE INDEX IF NOT EXISTS kra_companies_idx ON ov.konkurz_restrukturalizacia_actors (company_id);
    """

    with connection.cursor() as cursor:
        cursor.execute(create_index_query)


class Migration(migrations.Migration):

    dependencies = [
        ("dbs2021", "0004_add_fk"),
    ]

    operations = [
        migrations.RunPython(create_indexes),
    ]
