# Generated by Django 3.1.6 on 2021-03-19 19:32

from django.db import connection
from django.db import migrations


def create_view(apps, schema_editor):
    create_view_query = """
    CREATE OR REPLACE VIEW ov.companies_get AS
    SELECT cin, name, br_section, address_line, last_update,
    (   
        SELECT count(*)
        FROM ov.or_podanie_issues opi 
        WHERE opi.company_id = c.cin
    ) or_podanie_issues_count,
    (
        SELECT count(*)
        FROM ov.znizenie_imania_issues zii
        WHERE zii.company_id = c.cin
    ) znizenie_imania_issues_count,
    (
        SELECT count(*)
        FROM ov.likvidator_issues li
        WHERE li.company_id = c.cin
    ) likvidator_issues_count,
    (
        SELECT count(*)
        FROM ov.konkurz_vyrovnanie_issues kvi
        WHERE kvi.company_id = c.cin
    ) konkurz_vyrovnanie_issues_count,
    (
        SELECT count(*)
        FROM ov.konkurz_restrukturalizacia_actors kra
        WHERE kra.company_id = c.cin
    ) konkurz_restrukturalizacia_actors_count
    FROM ov.companies c;
    """

    with connection.cursor() as cursor:
        cursor.execute(create_view_query)


class Migration(migrations.Migration):

    dependencies = [
        ("dbs2021", "0005_create_indexes"),
    ]

    operations = [
        migrations.RunPython(create_view),
    ]
