# Generated by Django 3.1.6 on 2021-04-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs2021', '0007_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bulletinissues',
            table='ov"."bulletin_issues',
        ),
        migrations.AlterModelTable(
            name='companies',
            table='ov"."companies',
        ),
        migrations.AlterModelTable(
            name='konkurzrestrukturalizaciaactors',
            table='ov"."konkurz_restrukturalizacia_actors',
        ),
        migrations.AlterModelTable(
            name='konkurzrestrukturalizaciaissues',
            table='ov"."konkurz_restrukturalizacia_issues',
        ),
        migrations.AlterModelTable(
            name='konkurzrestrukturalizaciaproposings',
            table='ov"."konkurz_restrukturalizacia_proposings',
        ),
        migrations.AlterModelTable(
            name='konkurzvyrovnanieissues',
            table='ov"."konkurz_vyrovnanie_issues',
        ),
        migrations.AlterModelTable(
            name='likvidatorissues',
            table='ov"."likvidator_issues',
        ),
        migrations.AlterModelTable(
            name='orpodanieissuedocuments',
            table='ov"."or_podanie_issue_documents',
        ),
        migrations.AlterModelTable(
            name='orpodanieissues',
            table='ov"."or_podanie_issues',
        ),
        migrations.AlterModelTable(
            name='rawissues',
            table='ov"."raw_issues',
        ),
        migrations.AlterModelTable(
            name='znizenieimaniaceos',
            table='ov"."znizenie_imania_ceos',
        ),
        migrations.AlterModelTable(
            name='znizenieimaniaissues',
            table='ov"."znizenie_imania_issues',
        ),
    ]
